-- Campos dinâmicos em templates e contratos
-- Permite que a recepção preencha dados na geração e o paciente preencha ao assinar.

-- Extensão dos templates
ALTER TABLE contratos_templates
  ADD COLUMN IF NOT EXISTS campos_recepcao jsonb,  -- campos que a recepção preenche ao gerar o link
  ADD COLUMN IF NOT EXISTS campos_paciente  jsonb; -- campos que o paciente preenche ao assinar

-- Extensão dos contratos
ALTER TABLE contratos
  ADD COLUMN IF NOT EXISTS html_template_parcial text,    -- HTML com {{CAMPO}} dos campos do paciente ainda não preenchidos
  ADD COLUMN IF NOT EXISTS campos_paciente       jsonb,   -- copiado do template no momento de gerar o link
  ADD COLUMN IF NOT EXISTS dados_paciente_extras jsonb;   -- preenchido pelo paciente ao assinar

-- ── Atualizar ANEXO-9 pt1 — Recibo de Entrega de Documentos/Exames/Modelos ──
UPDATE contratos_templates SET
  corpo_html = '<div style="font-family: Arial, sans-serif; font-size: 10pt; color: #1a1a1a; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 20px;"><h2 style="text-align: center; text-decoration: underline; font-size: 13pt; margin-bottom: 8px;">RECIBOS DE ENTREGA DE DOCUMENTOS</h2><h3 style="text-align: center; text-decoration: underline; font-size: 11pt; margin-bottom: 24px;">RECIBO DE ENTREGA DE DOCUMENTOS/EXAMES/MODELOS</h3><p style="text-align: justify; margin-bottom: 16px;">Declaro ter recebido, na presente data, os documentos, exames e/ou modelo(s) abaixo relacionados, manifestando ter ciência de que estes são importantes registros técnicos de minha condição de saúde, fundamentais para adequado diagnóstico, planejamento e/ou acompanhamento do meu caso clínico.</p><p style="text-align: justify; margin-bottom: 20px;">Assumo ser de minha inteira responsabilidade a guarda destes itens, isentando o profissional e/ou estabelecimento de saúde de qualquer responsabilidade relativa aos documentos/itens ora entregues.</p><p style="margin-bottom: 16px;"><strong>Itens entregues:</strong></p><p style="margin-bottom: 20px; padding: 12px; background: #f9f9f9; border: 1px solid #ddd; border-radius: 6px; min-height: 48px;">{{itens_entregues}}</p><p style="margin-bottom: 8px;"><strong>Forma de entrega:</strong> {{forma_entrega}}</p><p style="text-align: center; margin-top: 48px; color: #666;">{{data_atual}}</p><p style="text-align: center; margin-top: 32px;">_________________________________</p><p style="text-align: center; font-size: 9pt; color: #666;">Assinatura do paciente — {{paciente_nome}}</p></div>',
  campos_recepcao = '[{"key":"itens_entregues","label":"Itens entregues (marque os aplicáveis)","type":"checkboxes","options":["Fotografias","Escaneamento intraoral","Pasta Ortodôntica","Radiografia Periapical","Radiografia Bitewing/Interproximal","Radiografia Panorâmica","Radiografia Cefalométrica/Telerradiografia","Radiografia Oclusal","Tomografia Computadorizada","Ressonância Magnética","Sialografia","Modelo de gesso","Laudo(s) de Exame(s)","Outro(s)"]},{"key":"forma_entrega","label":"Forma de entrega","type":"radio","options":["Meio físico","Arquivo digital – dispositivo removível","Arquivo digital – envio por e-mail"]}]'::jsonb,
  campos_paciente  = null
WHERE nome = 'Recibo de Entrega de Documentos/Exames/Modelos' AND vigente = true;

-- ── Atualizar ANEXO-9 pt2 — Recibo de Entrega de Cópia de Prontuário ─────────
UPDATE contratos_templates SET
  corpo_html = '<div style="font-family: Arial, sans-serif; font-size: 10pt; color: #1a1a1a; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 20px;"><h2 style="text-align: center; text-decoration: underline; font-size: 13pt; margin-bottom: 32px;">RECIBO DE ENTREGA DE CÓPIA DE PRONTUÁRIO</h2><p style="text-align: justify; margin-bottom: 16px;">Recebi, na presente data, a cópia integral do meu Prontuário Odontológico referente ao tratamento com a Clínica <strong>{{clinica_nome}}</strong>, contendo <strong>{{num_folhas}} folha(s)</strong>.</p><p style="text-align: justify; margin-bottom: 16px;">Manifesto ciência de que os dados constantes do meu Prontuário Odontológico são importantes registros técnicos de minha condição de saúde, fundamentais para diagnóstico e acompanhamento clínico.</p><p style="text-align: justify; margin-bottom: 24px;">Ao recebê-lo, assumo ser de minha inteira responsabilidade a guarda deste, em adequada segurança e sigilo de acesso, isentando o profissional e/ou estabelecimento de saúde de qualquer responsabilidade relativa ao documento ora entregue.</p><p style="margin-bottom: 8px;"><strong>Tipo de cópia:</strong> {{tipo_copia}}</p><p style="margin-bottom: 24px;"><strong>Forma de entrega:</strong> {{forma_entrega}}</p><p style="text-align: center; margin-top: 48px; color: #666;">{{data_atual}}</p><p style="text-align: center; margin-top: 32px;">_________________________________</p><p style="text-align: center; font-size: 9pt; color: #666;">Assinatura do paciente — {{paciente_nome}}</p></div>',
  campos_recepcao = '[{"key":"num_folhas","label":"Número de folhas","type":"number","placeholder":"Ex: 15"},{"key":"tipo_copia","label":"Tipo de cópia","type":"radio","options":["coloridas","em preto e branco"]},{"key":"forma_entrega","label":"Forma de entrega","type":"radio","options":["Meio físico","Arquivo digital – dispositivo removível","Arquivo digital – envio por e-mail"]}]'::jsonb,
  campos_paciente  = null
WHERE nome = 'Recibo de Entrega de Cópia de Prontuário' AND vigente = true;

-- ── Atualizar ANEXO-10 adulto — Autorização para Uso de Dados, Imagem e Voz ──
UPDATE contratos_templates SET
  corpo_html = '<div style="font-family: Arial, sans-serif; font-size: 10pt; color: #1a1a1a; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 20px;"><h2 style="text-align: center; text-decoration: underline; font-size: 13pt; margin-bottom: 32px;">AUTORIZAÇÃO PARA USO DE DADOS, IMAGEM E VOZ</h2><p style="margin-bottom: 6px;">Eu, <strong>{{paciente_nome}}</strong>,</p><p style="margin-bottom: 12px;">brasileiro(a), <strong>{{paciente_estado_civil}}</strong> (estado civil), RG de n.º <strong>{{paciente_rg}}</strong> – Órgão Expedidor <strong>{{paciente_orgao_expedidor}}</strong>, CPF/MF de n.º <strong>{{paciente_cpf}}</strong>,</p><p style="margin-bottom: 6px;">residente e domiciliado(a) na</p><p style="margin-bottom: 20px;"><strong>{{paciente_endereco}}</strong></p><p style="text-align: justify; margin-bottom: 16px;">venho, por meio deste termo, espontânea e livremente, <strong>AUTORIZAR</strong> o uso de dados do meu Prontuário Odontológico, de minhas imagens, áudios, vídeos, relativos ao tratamento odontológico a que me submeto com a Clínica <strong>{{clinica_nome}}</strong>, para fins de divulgação de assuntos odontológicos, especificamente nos seguintes meios:</p><p style="margin-bottom: 20px; padding: 12px; background: #f9f9f9; border: 1px solid #ddd; border-radius: 6px; min-height: 32px;"><strong>{{meios_divulgacao}}</strong></p><p style="text-align: justify; margin-bottom: 16px;">Abdicando de qualquer direito ou remuneração pelo uso destes registros, tendo a mim sido garantido que o profissional/estabelecimento sempre observará os preceitos éticos e legais vigentes relativos à Odontologia e previstos em legislação aplicável.</p><p style="text-align: justify; margin-bottom: 16px;">Fica o profissional/Clínica obrigado a não mais usar os dados e, sendo possível, a remover eventuais publicações neste ato autorizadas, se vier eu, a qualquer tempo, a revogar esta autorização.</p><p style="text-align: justify; margin-bottom: 32px;">Em manifestação autônoma de consentimento, de forma livre e esclarecida, firmo o presente, na forma da Lei 13.709/2018 (Lei Geral de Proteção de Dados — LGPD).</p><p style="text-align: center; margin-top: 48px; color: #666;">{{data_atual}}</p><p style="text-align: center; margin-top: 32px;">_________________________________</p><p style="text-align: center; font-size: 9pt; color: #666;">Assinatura do Paciente — {{paciente_nome}}</p></div>',
  campos_recepcao = '[{"key":"meios_divulgacao","label":"Meios de divulgação autorizados (marque os aplicáveis)","type":"checkboxes","options":["Instagram","Facebook / Meta","Site da clínica","YouTube","Artigo científico / publicação acadêmica","Apresentação em congresso / simpósio","Portfólio profissional","WhatsApp / mensagem direta"]}]'::jsonb,
  campos_paciente  = '[{"key":"estado_civil","label":"Estado civil","type":"select","options":["solteiro(a)","casado(a)","divorciado(a)","viúvo(a)","em união estável"]},{"key":"rg","label":"Número do RG","type":"text","placeholder":"Ex: 1234567"},{"key":"orgao_expedidor","label":"Órgão expedidor do RG","type":"text","placeholder":"Ex: SSP/SC"}]'::jsonb
WHERE nome = 'Autorização para Uso de Dados, Imagem e Voz' AND vigente = true;

-- ── Atualizar ANEXO-10 menor — Autorização (Paciente Menor) ──────────────────
UPDATE contratos_templates SET
  corpo_html = '<div style="font-family: Arial, sans-serif; font-size: 10pt; color: #1a1a1a; line-height: 1.7; max-width: 800px; margin: 0 auto; padding: 20px;"><h2 style="text-align: center; text-decoration: underline; font-size: 13pt; margin-bottom: 4px;">AUTORIZAÇÃO PARA USO DE DADOS, IMAGEM E VOZ</h2><h3 style="text-align: center; text-decoration: underline; font-size: 11pt; margin-bottom: 32px;">(PACIENTE MENOR)</h3><p style="margin-bottom: 6px;"><strong>Responsável legal:</strong></p><p style="margin-bottom: 6px;">Eu, <strong>{{responsavel_nome}}</strong>,</p><p style="margin-bottom: 12px;">brasileiro(a), <strong>{{responsavel_estado_civil}}</strong> (estado civil), RG de n.º <strong>{{responsavel_rg}}</strong> – Órgão Expedidor <strong>{{responsavel_orgao_expedidor}}</strong>, CPF/MF de n.º <strong>{{responsavel_cpf}}</strong>,</p><p style="margin-bottom: 6px;">residente e domiciliado(a) na</p><p style="margin-bottom: 20px;"><strong>{{responsavel_endereco}}</strong></p><p style="margin-bottom: 12px;"><strong>Responsável legal pelo(a) paciente menor:</strong> <strong>{{paciente_nome}}</strong></p><p style="text-align: justify; margin-bottom: 16px;">venho, por meio deste termo, espontânea e livremente, <strong>AUTORIZAR</strong> o uso de dados do Prontuário Odontológico do menor acima qualificado, bem como de suas imagens, áudios e vídeos, relativos ao tratamento odontológico a que se submete com a Clínica <strong>{{clinica_nome}}</strong>, para fins de divulgação de assuntos odontológicos, especificamente nos seguintes meios:</p><p style="margin-bottom: 20px; padding: 12px; background: #f9f9f9; border: 1px solid #ddd; border-radius: 6px; min-height: 32px;"><strong>{{meios_divulgacao}}</strong></p><p style="text-align: justify; margin-bottom: 16px;">Abdicando de qualquer direito ou remuneração pelo uso destes registros, tendo a mim sido garantido que o profissional/estabelecimento sempre observará os preceitos éticos e legais vigentes.</p><p style="text-align: justify; margin-bottom: 16px;">Fica o profissional/Clínica obrigado a não mais usar os dados e, sendo possível, a remover eventuais publicações neste ato autorizadas, se vier eu, como Responsável Legal, a qualquer tempo, revogar esta autorização.</p><p style="text-align: justify; margin-bottom: 32px;">Em manifestação autônoma de consentimento, de forma livre e esclarecida, firmo o presente, na forma da Lei 13.709/2018 (LGPD).</p><p style="text-align: center; margin-top: 48px; color: #666;">{{data_atual}}</p><p style="text-align: center; margin-top: 32px;">_________________________________</p><p style="text-align: center; font-size: 9pt; color: #666;">Assinatura do Responsável Legal — {{responsavel_nome}}</p></div>',
  campos_recepcao = '[{"key":"meios_divulgacao","label":"Meios de divulgação autorizados (marque os aplicáveis)","type":"checkboxes","options":["Instagram","Facebook / Meta","Site da clínica","YouTube","Artigo científico / publicação acadêmica","Apresentação em congresso / simpósio","Portfólio profissional","WhatsApp / mensagem direta"]}]'::jsonb,
  campos_paciente  = '[{"key":"responsavel_nome","label":"Nome completo do responsável legal","type":"text","placeholder":"Nome completo"},{"key":"responsavel_estado_civil","label":"Estado civil do responsável","type":"select","options":["solteiro(a)","casado(a)","divorciado(a)","viúvo(a)","em união estável"]},{"key":"responsavel_rg","label":"RG do responsável","type":"text","placeholder":"Ex: 1234567"},{"key":"responsavel_orgao_expedidor","label":"Órgão expedidor do RG","type":"text","placeholder":"Ex: SSP/SC"},{"key":"responsavel_cpf","label":"CPF do responsável","type":"cpf","placeholder":"000.000.000-00"},{"key":"responsavel_endereco","label":"Endereço do responsável","type":"text","placeholder":"Rua, número, bairro, cidade/UF"}]'::jsonb
WHERE nome = 'Autorização para Uso de Dados, Imagem e Voz (Paciente Menor)' AND vigente = true;
